<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="2">

  <testsuite name="signup.test"
    errors="0" failures="1" hostname="" id="" package="signup.test" skipped="0"
    tests="2" time="23.90" timestamp="Fri, 07 Apr 2017 22:23:02 GMT">
  
    <testcase name="Signup Page" classname="signup.test" time="7.359" assertions="2">

    

    
    </testcase>
  
    <testcase name="Register New User" classname="signup.test" time="16.54" assertions="2">
<system-out>[[ATTACHMENT|/Users/oyinda/Documents/Checkpoints/doc-management/screenshots/signup.test/Register-New-User_ERROR_Apr-07-2017-232325-GMT+0100.png]]</system-out>
      <failure message="Testing if the URL equals &quot;http://localhost:4000/&quot;.">    at Object.RegisterNewUser [as Register New User] (/Users/oyinda/Documents/Checkpoints/doc-management/client/test/e2e/signup.test.js:27:15)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
